"""Public API of the domain: import everything from `unicap.domain`."""

from unicap.domain.capacity import (
    Calculation,
    ChapterReport,
    FacultyNumbers,
    FacultyReport,
    HeadCount,
    Mix,
    NumbersReport,
    Roster,
    SpecializationCount,
    Violation,
    calculate,
    count_roster,
    evaluate_chapter,
    evaluate_faculty,
    evaluate_numbers,
    head_count,
    mix_of,
)
from unicap.domain.enums import (
    ContractStatus,
    ContractType,
    Degree,
    EmploymentType,
    ErrorCode,
    SpecializationType,
    TeacherKind,
    ViolationKind,
)
from unicap.domain.models import (
    Chapter,
    ChapterFaculty,
    Contract,
    DomainError,
    Employee,
    Faculty,
    Share,
    Specialization,
)
from unicap.domain.optimizer import (
    Outcome,
    Score,
    Strategy,
    optimize,
    outcome_of,
    substitutes_for,
)
from unicap.domain.ordering import in_staff_order, staff_order
from unicap.domain.recommender import (
    Hire,
    HireKind,
    Recommendation,
    RecommendationStrategy,
    recommend,
)
from unicap.domain.rounding import RoundingMode, round_count
from unicap.domain.salaries import SalaryClass, salary_class

__all__ = [
    "Calculation",
    "Chapter",
    "ChapterFaculty",
    "ChapterReport",
    "Contract",
    "ContractStatus",
    "ContractType",
    "Degree",
    "DomainError",
    "Employee",
    "EmploymentType",
    "ErrorCode",
    "Faculty",
    "FacultyNumbers",
    "FacultyReport",
    "HeadCount",
    "Hire",
    "HireKind",
    "Mix",
    "NumbersReport",
    "Outcome",
    "Recommendation",
    "RecommendationStrategy",
    "Roster",
    "RoundingMode",
    "SalaryClass",
    "Score",
    "Share",
    "Specialization",
    "SpecializationCount",
    "SpecializationType",
    "Strategy",
    "TeacherKind",
    "Violation",
    "ViolationKind",
    "calculate",
    "count_roster",
    "evaluate_chapter",
    "evaluate_faculty",
    "evaluate_numbers",
    "head_count",
    "in_staff_order",
    "mix_of",
    "optimize",
    "outcome_of",
    "recommend",
    "round_count",
    "salary_class",
    "staff_order",
    "substitutes_for",
]
