# Generated by Django 5.2.17 on 2026-10-02 06:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text="caps the chapter's capacity; empty: no cap", null=True, verbose_name='max students')),
                ('calculate_masters', models.BooleanField(default=True, help_text="off: masters are left out of this chapter's calculation", verbose_name='calculate masters')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ('-is_default', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='chapters_one_default_chapter')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.chapter', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('students_per_phd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='students per PhD')),
                ('min_staff_percentage', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='min staff percentage')),
                ('current_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='current students')),
                ('target_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='target students')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='max students')),
                ('min_specialized', models.PositiveIntegerField(blank=True, null=True, verbose_name='min specialized PhDs')),
                ('max_specialized', models.PositiveIntegerField(blank=True, null=True, verbose_name='max specialized PhDs')),
                ('min_supported', models.PositiveIntegerField(blank=True, null=True, verbose_name='min supported PhDs')),
                ('max_supported', models.PositiveIntegerField(blank=True, null=True, verbose_name='max supported PhDs')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='app.chapter', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('contract_type', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime')], default='fulltime', max_length=16, verbose_name='contract type')),
                ('employment_type', models.CharField(choices=[('staff', 'staff'), ('borrowed', 'borrowed')], default='staff', max_length=16, verbose_name='employment type')),
                ('degree', models.CharField(choices=[('phd', 'PhD'), ('master', 'master')], default='phd', max_length=16, verbose_name='degree')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='signing order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='app.chapter', verbose_name='chapter')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='app.employee', verbose_name='employee')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='app.faculty', verbose_name='faculty')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='app.chapter', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'specialization',
                'verbose_name_plural': 'specializations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FacultySpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_type', models.CharField(choices=[('specialized', 'specialized'), ('supported', 'supported')], default='specialized', max_length=16, verbose_name='type')),
                ('percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percentage')),
                ('min_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='min percentage')),
                ('max_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='max percentage')),
                ('min_teachers', models.PositiveIntegerField(blank=True, null=True, verbose_name='min teachers')),
                ('max_teachers', models.PositiveIntegerField(blank=True, null=True, verbose_name='max teachers')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='app.faculty', verbose_name='faculty')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shares', to='app.specialization', verbose_name='specialization')),
            ],
            options={
                'verbose_name': 'accepted specialization',
                'verbose_name_plural': 'accepted specializations',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='app.specialization', verbose_name='specialization'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='edu_faculty_unique_name_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.CheckConstraint(condition=models.Q(('students_per_phd__gt', 0)), name='edu_faculty_students_per_phd_positive'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('contract_type', 'parttime'), ('employment_type', 'staff'), _negated=True), name='hr_contract_parttime_is_borrowed'),
        ),
        migrations.AddConstraint(
            model_name='specialization',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='edu_specialization_unique_name_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='facultyspecialization',
            constraint=models.UniqueConstraint(fields=('faculty', 'specialization'), name='edu_faculty_specialization_unique'),
        ),
    ]
