# Generated by Django 5.2.17 on 2026-10-02 07:02

import django.core.validators
import unicap.app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('report', models.CharField(choices=[('capacity', 'capacity report'), ('faculty_staff', 'faculty staff')], max_length=32, verbose_name='report')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=8, verbose_name='language')),
                ('file', models.FileField(help_text='a Word (.docx) file holding docxtpl tags such as {{ chapter.name }}', upload_to='report-templates/', validators=[django.core.validators.FileExtensionValidator(['docx']), unicap.app.validators.validate_docx_template], verbose_name='file')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'report template',
                'verbose_name_plural': 'report templates',
                'ordering': ('report', 'language'),
                'constraints': [models.UniqueConstraint(fields=('report', 'language'), name='app_report_template_unique_report_language')],
            },
        ),
    ]
