# Generated by Django 5.2.17 on 2026-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='UniCap', max_length=100, verbose_name='project name')),
                ('per_page', models.PositiveSmallIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (250, '250')], default=25, verbose_name='rows per page')),
                ('modal_size', models.CharField(choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='lg', max_length=8, verbose_name='modal size')),
                ('resizable_modals', models.BooleanField(default=True, help_text="drag a modal's corner to resize it, or maximize it", verbose_name='resizable modals')),
                ('remember_table_state', models.BooleanField(default=True, help_text='a table opens again with the filters, search, sorting and page it was left with', verbose_name='remember table state')),
            ],
            options={
                'verbose_name': 'app settings',
            },
        ),
        migrations.CreateModel(
            name='ChapterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_page', models.PositiveSmallIntegerField(blank=True, choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (250, '250')], help_text="empty: the app's default", null=True, verbose_name='rows per page')),
                ('form_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='form modal size')),
                ('details_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='details modal size')),
            ],
            options={
                'verbose_name': 'chapters settings',
            },
        ),
        migrations.CreateModel(
            name='ContractSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_page', models.PositiveSmallIntegerField(blank=True, choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (250, '250')], help_text="empty: the app's default", null=True, verbose_name='rows per page')),
                ('form_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='form modal size')),
                ('details_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='details modal size')),
            ],
            options={
                'verbose_name': 'contracts settings',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_page', models.PositiveSmallIntegerField(blank=True, choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (250, '250')], help_text="empty: the app's default", null=True, verbose_name='rows per page')),
                ('form_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='form modal size')),
                ('details_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='details modal size')),
            ],
            options={
                'verbose_name': 'employees settings',
            },
        ),
        migrations.CreateModel(
            name='FacultySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_page', models.PositiveSmallIntegerField(blank=True, choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (250, '250')], help_text="empty: the app's default", null=True, verbose_name='rows per page')),
                ('form_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='xl', help_text="empty: the app's default", max_length=8, verbose_name='form modal size')),
                ('details_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='xl', help_text="empty: the app's default", max_length=8, verbose_name='details modal size')),
            ],
            options={
                'verbose_name': 'faculties settings',
            },
        ),
        migrations.CreateModel(
            name='SpecializationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_page', models.PositiveSmallIntegerField(blank=True, choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (250, '250')], help_text="empty: the app's default", null=True, verbose_name='rows per page')),
                ('form_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='form modal size')),
                ('details_modal_size', models.CharField(blank=True, choices=[('md', 'medium'), ('lg', 'large'), ('xl', 'extra large'), ('full', 'full width')], default='', help_text="empty: the app's default", max_length=8, verbose_name='details modal size')),
            ],
            options={
                'verbose_name': 'specializations settings',
            },
        ),
    ]
