# Generated by Django 5.2.17 on 2026-10-02 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('scope', models.CharField(choices=[('system', 'whole system'), ('chapter', 'chapter'), ('section', 'section')], max_length=16, verbose_name='scope')),
                ('section', models.CharField(blank=True, choices=[('specializations', 'specializations'), ('faculties', 'faculties'), ('employees', 'employees'), ('contracts', 'contracts')], default='', max_length=32, verbose_name='section')),
                ('chapter_name', models.CharField(blank=True, max_length=255, verbose_name='chapter')),
                ('file', models.FileField(upload_to='backups/', verbose_name='file')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='app.chapter', verbose_name='chapter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
                'ordering': ('-created_at', '-pk'),
                'permissions': (('restore_backup', 'Can restore a backup'),),
            },
        ),
    ]
