# Generated by Django 5.2.17 on 2026-10-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_backup'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='contract',
            name='hr_contract_parttime_is_borrowed',
            constraint=models.CheckConstraint(condition=models.Q(('contract_type', 'parttime'), ('employment_type', 'staff'), _negated=True), name='hr_contract_parttime_is_borrowed', violation_error_message='a parttime contract is always borrowed.'),
        ),
        migrations.AlterConstraint(
            model_name='faculty',
            name='edu_faculty_students_per_phd_positive',
            constraint=models.CheckConstraint(condition=models.Q(('students_per_phd__gt', 0)), name='edu_faculty_students_per_phd_positive', violation_error_message='students per PhD must be positive.'),
        ),
    ]
