# Generated by Django 5.2.17 on 2026-10-02 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_constraint_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='optimizer_rounds',
            field=models.PositiveSmallIntegerField(default=20, help_text='how many times the optimizer goes over every contract looking for a better place: more can find better placements, but takes longer', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='optimizer rounds'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='masters_per_phd',
            field=models.PositiveSmallIntegerField(default=2, help_text='how many masters are worth one PhD in capacity', validators=[django.core.validators.MinValueValidator(1)], verbose_name='masters per PhD'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='masters_rounding',
            field=models.CharField(choices=[('floor', 'down (floor)'), ('ceiling', 'up (ceiling)'), ('half_up', 'mathematical (half up)'), ('half_down', 'half down'), ('half_even', "half to even (banker's)")], default='floor', help_text="how a faculty's masters round to whole PhDs (e.g. one master alone)", max_length=16, verbose_name='masters rounding'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='specialized_masters_only',
            field=models.BooleanField(default=False, help_text='on: a master is counted only in a faculty where their specialization is specialized', verbose_name='specialized masters only'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='max_share_rounding',
            field=models.CharField(choices=[('floor', 'down (floor)'), ('ceiling', 'up (ceiling)'), ('half_up', 'mathematical (half up)'), ('half_down', 'half down'), ('half_even', "half to even (banker's)")], default='floor', help_text="a specialization's max percentage in whole teachers: the most it may count", max_length=16, verbose_name='max share rounding'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='min_share_rounding',
            field=models.CharField(choices=[('floor', 'down (floor)'), ('ceiling', 'up (ceiling)'), ('half_up', 'mathematical (half up)'), ('half_down', 'half down'), ('half_even', "half to even (banker's)")], default='ceiling', help_text="a specialization's min percentage in whole teachers: the fewest it needs", max_length=16, verbose_name='min share rounding'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='staff_rounding',
            field=models.CharField(choices=[('floor', 'down (floor)'), ('ceiling', 'up (ceiling)'), ('half_up', 'mathematical (half up)'), ('half_down', 'half down'), ('half_even', "half to even (banker's)")], default='ceiling', help_text='the min staff percentage in whole fulltime staff: the fewest it needs', max_length=16, verbose_name='min staff rounding'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='contract', to='app.employee', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='app.faculty', verbose_name='faculty'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.CheckConstraint(condition=models.Q(('masters_per_phd__gt', 0)), name='chapters_masters_per_phd_positive', violation_error_message='masters per PhD must be positive.'),
        ),
    ]
