# Generated by Django 5.2.17 on 2026-10-02 17:45

import django.core.validators
from django.db import migrations, models


def masters_to_rows(apps, schema_editor):
    """Each chapter's masters settings move onto its faculties and their accepted rows.

    - calculate masters off: every row leaves masters out
    - specialized masters only: supported rows leave masters out
    - masters per PhD: every row; masters rounding: every faculty
    """
    Chapter = apps.get_model("app", "Chapter")
    Faculty = apps.get_model("app", "Faculty")
    FacultySpecialization = apps.get_model("app", "FacultySpecialization")

    for chapter in Chapter.objects.all():
        Faculty.objects.filter(chapter=chapter).update(masters_rounding=chapter.masters_rounding)

        rows = FacultySpecialization.objects.filter(faculty__chapter=chapter)
        rows.update(masters_per_phd=chapter.masters_per_phd)

        if not chapter.calculate_masters:
            rows.update(calculate_masters=False)
        elif chapter.specialized_masters_only:
            rows.filter(specialization_type="supported").update(calculate_masters=False)


def masters_to_chapters(apps, schema_editor):
    """Back: a chapter takes its first row's masters per PhD and its first faculty's rounding."""
    Chapter = apps.get_model("app", "Chapter")
    Faculty = apps.get_model("app", "Faculty")
    FacultySpecialization = apps.get_model("app", "FacultySpecialization")

    for chapter in Chapter.objects.all():
        rows = FacultySpecialization.objects.filter(faculty__chapter=chapter)
        faculty = Faculty.objects.filter(chapter=chapter).first()
        row = rows.first()
        chapter.calculate_masters = rows.filter(calculate_masters=True).exists() or not rows
        chapter.specialized_masters_only = (
            rows.filter(specialization_type="supported", calculate_masters=False).exists()
            and rows.filter(specialization_type="specialized", calculate_masters=True).exists()
        )
        chapter.masters_per_phd = row.masters_per_phd if row else 2
        chapter.masters_rounding = faculty.masters_rounding if faculty else "floor"
        chapter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_masters_rounding_and_delete_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='masters_rounding',
            field=models.CharField(choices=[('floor', 'down (floor)'), ('ceiling', 'up (ceiling)'), ('half_up', 'mathematical (half up)'), ('half_down', 'half down'), ('half_even', "half to even (banker's)")], default='floor', help_text="the faculty's masters in whole PhDs (e.g. one master alone)", max_length=16, verbose_name='masters rounding'),
        ),
        migrations.AddField(
            model_name='facultyspecialization',
            name='calculate_masters',
            field=models.BooleanField(default=True, help_text="off: the specialization's masters are left out of this faculty", verbose_name='calculate masters'),
        ),
        migrations.AddField(
            model_name='facultyspecialization',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'fulltime'), ('parttime', 'parttime')], default='', help_text='only this contract type counts for the specialization here; empty: any', max_length=16, verbose_name='contract type'),
        ),
        migrations.AddField(
            model_name='facultyspecialization',
            name='masters_per_phd',
            field=models.PositiveSmallIntegerField(default=2, help_text='how many of its masters are worth one PhD', validators=[django.core.validators.MinValueValidator(1)], verbose_name='masters per PhD'),
        ),
        migrations.AddConstraint(
            model_name='facultyspecialization',
            constraint=models.CheckConstraint(condition=models.Q(('masters_per_phd__gt', 0)), name='edu_share_masters_per_phd_positive', violation_error_message='masters per PhD must be positive.'),
        ),
        migrations.RunPython(masters_to_rows, masters_to_chapters),
        migrations.RemoveConstraint(
            model_name='chapter',
            name='chapters_masters_per_phd_positive',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='calculate_masters',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='masters_per_phd',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='masters_rounding',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='specialized_masters_only',
        ),
    ]
