# Generated by Django 5.2.17 on 2026-10-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_masters_per_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report',
            field=models.CharField(choices=[('capacity', 'capacity report'), ('faculty_staff', 'faculty staff'), ('capacity_pivot', 'capacity pivot'), ('faculty_staff_pivot', 'faculty staff pivot')], max_length=32, verbose_name='report'),
        ),
    ]
