# Generated by Django 5.2.17 on 2026-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reporttemplate_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report',
            field=models.CharField(choices=[('capacity', 'capacity report'), ('faculty_staff', 'faculty staff'), ('capacity_pivot', 'capacity pivot'), ('faculty_staff_pivot', 'faculty staff pivot'), ('capacity_audit', 'calculation audit')], max_length=32, verbose_name='report'),
        ),
    ]
