# Generated by Django 5.2.17 on 2026-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_reporttemplate_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='excluded_faculties',
            field=models.ManyToManyField(blank=True, help_text='signed to one of these faculties, the contract is never counted there', related_name='excluded_employees', to='app.faculty', verbose_name='cannot be counted in'),
        ),
    ]
