# Generated by Django 5.2.17 on 2026-10-05 17:14

import unicap.app.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_employee_excluded_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(storage=unicap.app.storages.PrivateStorage(), upload_to='backups/', verbose_name='file'),
        ),
    ]
