# Generated by Django 5.2.17 on 2026-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_backup_private_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='once signed, the contract cannot be moved to another faculty or unsigned', verbose_name='locked to its faculty'),
        ),
    ]
